name: TeamCity deployment

on: push

jobs:
  # Собирается бекенд и деплоится на стейдж/review app
  backend:
    uses: ./.github/workflows/backend-stage.yaml

  # Собирается бекенд и деплоится на стейдж/review app
  frontend:
    uses: ./.github/workflows/frontend-stage.yaml

  # Прогоняются API тесты
  automation-api:
    needs: [ backend, frontend ]
    uses: ./.github/workflows/automation.yaml
    with:
      package: api

  # Прогоняются UI тесты
  automation-ui:
    needs: [ backend, frontend ]
    uses: ./.github/workflows/automation.yaml
    with:
      package: ui